name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
        
  ui_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Execute all tests
      run: mvn clean test --file pom.xml
    - name: Test Reporter UI
      uses: dorny/test-reporter@v1.4.3
      if: always()
      with:
        name: junit execution report ui
        path: "**/surefire-reports/TEST-*.xml"
        reporter: java-junit
